// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzuzepthtnckpspdlaap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dXplcHRodG5ja3BzcGRsYWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDI3MjgsImV4cCI6MjA3MzM3ODcyOH0.TKTnYGi8SxzpgHsYShha4LHwvTxEVF6Y3Wbit4gIA1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});